version: '3'

services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres #db
      POSTGRES_USER: postgres #user
      POSTGRES_PASSWORD: postgres #pass

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    depends_on:
      - postgres
      - redis
      - django